//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSharing.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.CarRentals = new HashSet<CarRental>();
        }
    
        public int IdCar { get; set; }
        public string VIN { get; set; }
        public int TypeOfCar { get; set; }
        public int CarMake { get; set; }
        public int CarColor { get; set; }
        public int TypeEngine { get; set; }
    
        public virtual CarColor CarColor1 { get; set; }
        public virtual CarMake CarMake1 { get; set; }
        public virtual TypeEngine TypeEngine1 { get; set; }
        public virtual TypeOfCar TypeOfCar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarRental> CarRentals { get; set; }
    }
}
