//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSharing.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRental
    {
        public int IdCarRental { get; set; }
        public int CarId { get; set; }
        public int UserId { get; set; }
        public int CityId { get; set; }
        public System.DateTime DateTimeStart { get; set; }
        public Nullable<System.DateTime> DateTimeEnd { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual City City { get; set; }
        public virtual User User { get; set; }

        public static implicit operator string(CarRental v)
        {
            throw new NotImplementedException();
        }
    }
}
